### ISSUE TITLE
fix: action version 1.1.x breaks chmod and chown operations in scripts, they fail silently

### ISSUE THREAD

**Issue by qoijjj** [blue-build/cli#100]
https://github.com/secureblue/secureblue/actions/runs/8058224104

**Comment by qoijjj** [comment]
confirmed repro on 1.1.1

**Comment by gmpinder** [comment]
Is this related to #97 ?

**Comment by xynydev** [comment]
Seems like you created three related issues from the same problem:
#98, #97, and #100.

Is this a problem you can describe more clearly and supply minimal reproduction steps to the maintainers? Do you know what should be done about this or if there are possible alternate causes for this problem?

**Comment by qoijjj** [comment]
@xynydev They are related but not the same, I figured it would be valuable to have tickets tracking each. 

> Is this a problem you can describe more clearly and supply minimal reproduction steps to the maintainers? 

I provided much more context on discord, but I can copy it here if needed. In short, if you use `chmod` or `chown` in a script in bluebuild, the changes persist into the image in 1.0.2, but not in 1.1.x

**Comment by gmpinder** [comment]
@qoijjj if you could paste a link to your failing script here, I'll be sure to add it to our integration tests

**Comment by qoijjj** [comment]
doing something like this:

```
chown root:root /usr/bin/bwrap
chmod u+s /usr/bin/bwrap
```
and then afterwards, the script would need to check that the right bits are set on that file

**Comment by gmpinder** [comment]
#104 Added an integration test for one of secureblue's builds
