### ISSUE TITLE
dracut error on kernel replace

### ISSUE THREAD

**Issue by antuan1996** [blue-build/cli#119]
I try to replace the default kernel in my image. I've set up adding new repos and launch of custom scripts using the 'script' module in my recipe.
If launch these commands
```
rpm-ostree cliwrap install-to-root / && \
rpm-ostree override remove kernel kernel-core kernel-modules kernel-modules-core kernel-modules-extra --install kernel-cachyos 
``` 
I get the next error in action logs:
```error: rpm-ostree kernel-install wrapper: Running dracut: Invalid cross-device link (os error 18)```

The pipeline does not fail, but if I try to boot from the built image it will stuck on boot screen.

**Comment by fiftydinar** [comment]
Try to use rpm-ostree override replace method instead:

```
    rpm-ostree cliwrap install-to-root / && \
    rpm-ostree override replace --experimental --from repo=copr:copr.fedorainfracloud.org:bieszczaders:kernel-cachyos kernel kernel-core kernel-modules kernel-modules-core kernel-modules-extra
```

**Comment by antuan1996** [comment]
I use the same commands in 'startingpoint' based repository and it works fine.
I believe the error message `Invalid cross-device link` implies something is wrong in mounting or path mapping settings.

**Comment by gmpinder** [comment]
Mind posting a link to your repo so I can test it later?

**Comment by antuan1996** [comment]
Here is my repository based on new template: https://github.com/antuan1996/formile-cachyos-ublue
Build logs: [link](https://productionresultssa0.blob.core.windows.net/actions-results/692f8d9b-c8d5-4a4c-8fa4-984610c4c515/workflow-job-run-71fa8021-0738-5b76-c76c-3b91608c36e3/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-03-16T07%3A29%3A16Z&sig=hGvpdNj%2Ba8FuUX3CnGTK2EPbxW1uaaM0niT3RF6yBtY%3D&sp=r&spr=https&sr=b&st=2024-03-16T07%3A19%3A11Z&sv=2021-12-02)

**Comment by gmpinder** [comment]
So I think we may have a fix that we pushed to the main branch. You can try it out in your Github action by setting `use_unstable_cli` to true.

**Comment by antuan1996** [comment]
I confirm the problem is gone. Thank you very much!
