### ISSUE TITLE
cosign template assumes github too eagerly

### ISSUE THREAD

**Issue by Arcayr** [blue-build/cli#133]
this part of the cosign containerfile generated as part of the build assumes ghcr.io is the registry if the `$GITHUB_REPOSITORY_OWNER` environment variable is present. this is true not only for github but also for gitea-likes due to their intended compatibility with github actions.

https://github.com/blue-build/cli/blob/aa1de26ad9a6e0866146890569da199c8e9d3f33/template/templates/Containerfile.j2#L38-L44

this occurs despite setting the registry in my `build.yml` as an environment variable (`$IMAGE_REGISTRY`) to the runner container, as well as passing the value as `--registry` to `bluebuild build`.

my suggestion is to allow `$IMAGE_REGISTRY` to be defined by the `bluebuild-cli` user and use `$GITHUB_REPOSITORY_OWNER` as a fallback. it looks like the intent is there but it got dropped somewhere while migrating to the module version of `signing`.

**Comment by gmpinder** [comment]
I'll take a look and try to get this fixed for the next patch
