### ISSUE TITLE
fix: `cosign sign` is not recursive leading to podman being unable to pull the image

### ISSUE THREAD

**Issue by prydom** [blue-build/cli#147]
## Current behavior

While images that are built and signed with bluebuild can be verified by rpm-ostree/bootc, they are not trusted by `podman image pull` with the error `Error: copying system image from manifest list: Source image rejected: A signature was required, but no signature exists`.

## Expected behavior

Images can be pulled with `podman`.

## Additional details

I debugged this behavior using the `--log-level=debug` flag and determined it was because `podman` is checking for signatures on each image referred to in the manifest which the `latest` tag points at. The image is a manifest, even though it only has one architecture, due to this feature of Docker: https://docs.docker.com/build/attestations/attestation-storage/.

In this example log below, `ghcr.io/prydom/fedora-kinoite-laptop:20240328` points at a manifest `ghcr.io/prydom/fedora-kinoite-laptop:20240328@sha256:be2c706d0550302359d06dc83d105f86e4692656bb14c758ab04ac0ca82e1e24` which matches the image `ghcr.io/prydom/fedora-kinoite-laptop:20240328@sha256:d071d8871599465621b412411f2e1e040d815632f41870b4d20f705979a1e693`.

be2c706d0550302359d06dc83d105f86e4692656bb14c758ab04ac0ca82e1e24 is signed by `cosign` (you can see this [here](https://github.com/prydom/my-ostree-build/actions/runs/8469601016/job/23205303511#step:2:5388)) but d071d8871599465621b412411f2e1e040d815632f41870b4d20f705979a1e693 is not. Which you can observe in the logs below.

I'm keeping this image private on ghcr.io so you probably can't directly inspect the image but it should be trivial to reproduce.

##  Workaround

I am able to workaround this by resigning the manifest using the command `cosign sign --key=env://OSIGN_PRIVATE_KEY --recursive ghcr.io/prydom/fedora-kinoite-laptop@sha256:<MANIFEST-HASH>`.

## Possible solution

Unless there's some side effect I'm unaware of, I suggest we add `--recursive` to `sign_images()` and `sign_priv_public_pair()` in `src/commands/build.rs`. I'm happy to contribute this, if you'd like.

## Bluebuild version

I'm pinned to this build of bluebuild, `ghcr.io/blue-build/cli@sha256:ee7efa99c8a0cec6c229333d63bf59fce301bdca53361caf3b3debd855424ef8`. Which corresponds to
this push I believe https://github.com/blue-build/cli/commit/189141924baccb04349330348428f576ac6b2a76.

I just noticed the recent release and will upgrade to that.

## Podman logs

```
DEBU[0000] Trying to access "ghcr.io/prydom/fedora-kinoite-laptop:20240328" 
DEBU[0000] No credentials matching ghcr.io/prydom/fedora-kinoite-laptop found in /run/user/1000/containers/auth.json 
DEBU[0000] Found credentials for ghcr.io/prydom/fedora-kinoite-laptop in credential helper containers-auth.json in file /var/home/$USER/.config/containers/auth.json 
DEBU[0000]  Lookaside configuration: using "docker" namespace ghcr.io/prydom/fedora-kinoite-laptop 
DEBU[0000]  Lookaside configuration: using "default-docker" configuration 
DEBU[0000]  No signature storage configuration found for ghcr.io/prydom/fedora-kinoite-laptop:20240328, using built-in default file:///var/home/$USER/.local/share/containers/sigstore 
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/ghcr.io 
DEBU[0000]  Sigstore attachments: using "docker" namespace ghcr.io/prydom/fedora-kinoite-laptop 
DEBU[0000] GET https://ghcr.io/v2/                      
DEBU[0000] Ping https://ghcr.io/v2/ status 401          
DEBU[0000] GET https://ghcr.io/token?account=prydom&scope=repository%3Aprydom%2Ffedora-kinoite-laptop%3Apull&service=ghcr.io 
DEBU[0002] Increasing token expiration to: 60 seconds   
DEBU[0002] GET https://ghcr.io/v2/prydom/fedora-kinoite-laptop/manifests/20240328 
DEBU[0002] Content-Type from manifest GET is "application/vnd.oci.image.index.v1+json" 
DEBU[0002] Using SQLite blob info cache at /var/home/$USER/.local/share/containers/cache/blob-info-cache-v1.sqlite 
DEBU[0002] Source is a manifest list; copying (only) instance sha256:d071d8871599465621b412411f2e1e040d815632f41870b4d20f705979a1e693 for current system 
DEBU[0002] GET https://ghcr.io/v2/prydom/fedora-kinoite-laptop/manifests/sha256:d071d8871599465621b412411f2e1e040d815632f41870b4d20f705979a1e693 
DEBU[0002] Content-Type from manifest GET is "application/vnd.oci.image.manifest.v1+json" 
DEBU[0003] IsRunningImageAllowed for image docker:ghcr.io/prydom/fedora-kinoite-laptop:20240328 
DEBU[0003]  Using transport "docker" specific policy section ghcr.io/prydom/fedora-kinoite-laptop 
DEBU[0003] Reading /var/home/$USER/.local/share/containers/sigstore/prydom/fedora-kinoite-laptop@sha256=d071d8871599465621b412411f2e1e040d815632f41870b4d20f705979a1e693/signature-1 
DEBU[0003] Looking for sigstore attachments in ghcr.io/prydom/fedora-kinoite-laptop:sha256-d071d8871599465621b412411f2e1e040d815632f41870b4d20f705979a1e693.sig 
DEBU[0003] GET https://ghcr.io/v2/prydom/fedora-kinoite-laptop/manifests/sha256-d071d8871599465621b412411f2e1e040d815632f41870b4d20f705979a1e693.sig 
DEBU[0003] Content-Type from manifest GET is "application/json" 
DEBU[0003] Fetching sigstore attachment manifest failed, assuming it does not exist: reading manifest sha256-d071d8871599465621b412411f2e1e040d815632f41870b4d20f705979a1e693.sig in ghcr.io/prydom/fedora-kinoite-laptop: manifest unknown 
DEBU[0003] Requirement 0: denied, done                  
DEBU[0003] Error pulling candidate ghcr.io/prydom/fedora-kinoite-laptop:20240328: copying system image from manifest list: Source image rejected: A signature was required, but no signature exists 
Error: copying system image from manifest list: Source image rejected: A signature was required, but no signature exists
DEBU[0003] Shutting down engines
```

**Comment by gmpinder** [comment]
Contribution would be welcome! Had no clue podman did that kind of check.

I'm taking a break because of IRL events, but I'd be fine approving a PR

**Comment by prydom** [comment]
Fix worked and can be seen in action here: https://github.com/prydom/my-ostree-build/actions/runs/8486854854/job/23253890515#step:2:4703

`podman` is now able to pull images with the policy.json supplied by bluebuild.
