### ISSUE TITLE
feat: Enable squashing of images

### ISSUE THREAD

**Issue by gmpinder** [blue-build/cli#152]
I was doing some research into how the previous build system worked regarding layers being squashed. I found a particularly [useful issue thread](https://github.com/containers/buildah/issues/1234#issuecomment-534685356) in the buildah repo that explained the default squashing strategy for the various tool. In short it goes:

- `buildah` - default squash layers after base image
- `podman` - default no squash
- `docker` - default no squash

Since the original build system used `buildah`, the layers were being squashed. Since `podman` has been trying to follow the same implementation as `docker`, it followed the same pattern of not squashing.

**Comment by gmpinder** [comment]
Just doing some more searching, seems as though `docker buildx` does not support squashing (https://github.com/docker/buildx/issues/727).

This makes things a little more complicated for use in GHA since `docker` is our default builder atm. This might end up requiring tradeoffs between making use of cache in GHA vs squashing. There will probably also have to be an option for creating a compatible `Containerfile` template for the `podman`/`buildah` versions for `ubuntu-latest` VMs in GHA.

**Comment by xynydev** [comment]
> This makes things a little more complicated for use in GHA since docker is our default builder atm. This might end up requiring tradeoffs between making use of cache in GHA vs squashing. There will probably also have to be an option for creating a compatible Containerfile template for the podman/buildah versions for ubuntu-latest VMs in GHA.

Maybe something that could be fixed with #143? Make some trade-off for the users by default (we should discuss that), then let them change it.

**Comment by gmpinder** [comment]
Yeah I was thinking of working on that issue first to start on this one. There's still the issue of GHA VMs not having the right versions of `buildah` and `podman`. Maybe this could also be a case where we can encourage users to run their builds using the CLI images we build (https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container). We are in a weird spot right now cause of Ubuntu LTS runners.

**Comment by gmpinder** [comment]
Merged in #155
