### ISSUE TITLE
bug: Unable to rebase to local build

### ISSUE THREAD

**Issue by 34N0** [blue-build/cli#154]
Hello while rebasing to a local [secureblue](https://github.com/secureblue/secureblue) build i get the following error:
```console
$ bluebuild rebase config/recipes/general/recipe-silverblue-main-userns.yml
...
$ error: While pulling silverblue-main-userns-hardened: Remote "ostree-unverified-image" not found
$ ERROR => Failed to rebase to silverblue-main-userns-hardened
```
The error is from the subprocess spawned in
https://github.com/blue-build/cli/blob/e9c96e204d9ad45e9196f0aed8d377c1191e4553/src/commands/local.rs#L134-L138

Thank you for your help!

**Comment by gmpinder** [comment]
Yeah this bug has already been fixed in main. I found it shortly after the release. This will be going out in the next patch. Sorry for not catching it in time.
