### ISSUE TITLE
fix: check if current transaction is ongoing in rebase command

### ISSUE THREAD

**Issue by 34N0** [blue-build/cli#159]
When automatic upgrades are enabled users might use the rebase command while a transaction is ongoing. Currently in main the `rpm-ostree rebase` subprocess terminates with `Transaction in progress:`. This is bad UX since this leads users to have to restart the rebuild process which can take minutes.

I think the command should either check the `rpm-ostree` status initially and inform the user or much simpler, when the final rebase subprocess terminates inform the user about the built file in `/etc/bluebuild`. 

Tell me what you think about this i could work on this if you think this is an issue as well.

**Comment by gmpinder** [comment]
Yeah that's a good idea. We will already be determining if we need to rebase vs. upgrade when we make the change to consolidating the two commands into `switch`. The issue for that is #65 and there's a PR out in draft for when I get around to finishing it (#116 ). This can be planned to be added to that PR. It would end up going out in `v0.9.0`.
