### ISSUE TITLE
bug: multiple module types in one .yml file fails silently

### ISSUE THREAD

**Issue by michaelhaaf** [blue-build/cli#162]
## Background 

[The current documentation about `recipe.yml` files](https://blue-build.org/reference/recipe/#modules) does explain clearly that a `modules` key is required when you have more than one module `type` in the same file.

Let's say you didn't notice this, and you extend a flat module file (with only one type of module) by adding a second type of module. Here's a simple example, where a working `common-fonts.yml` with just the `fonts` module has an `rpm-ostree` module added to it like so:

```diff
diff --git a/config/common-fonts.yml b/config/common-fonts.yml
--- a/config/common-fonts.yml
+++ b/config/common-fonts.yml
type: fonts
fonts:
   nerd-fonts:
     - Iosevka
     - FiraCode
     - JetBrainsMono
     - NerdFontsSymbolsOnly

+type: rpm-ostree
+install:
+  - ibm-plex-fonts-all
```

What happens?

## Current behavior

In a real-life example with a very similar change: [The build succeeds, despite a "duplicate type" error being logged (link should open at line # of error log)](https://github.com/michaelhaaf/bluebuild-custom/actions/runs/8513216960/job/23316438577#step:2:534).

Note: the module fails to complete. I only noticed because I didn't actually test this on a new system until 2 weeks later, and none of the fonts I'm used to being present were there.

## Expected behavior 

Build should fail -- the module failed to run, in this case the fonts failed to install.

## Test environment

BlueBuild GitHub Action (not reproduced locally). See link in "Current behavior" section

## Example recipe

Here are the module recipes used in the "Current Behavior" section:

- Before breaking change (font module works as expected): https://github.com/michaelhaaf/bluebuild-custom/blob/40f40f1aacf1ff6e4d7b94ee7d70a39f4f289607/config/common-fonts.yml
- After breaking change (font module fails silently, rest of build succeeds): https://github.com/michaelhaaf/bluebuild-custom/blob/c39ef603f79a5b6727b842117a23c36e0558dc61/config/common-fonts.yml

**Comment by gmpinder** [comment]
Ah good catch. I'll be sure to have it properly fail
