### ISSUE TITLE
bug: Error: bad file '-': yaml: line 2: found unexpected end of stream

### ISSUE THREAD

**Issue by fiftydinar** [blue-build/cli#170]
I started to get this error now, without changing anything in `default-flatpaks` recipe file:

https://github.com/fiftydinar/gidro-os/actions/runs/8869108032/job/24349434130#step:2:1898

This happens when using unstable CLI, while stable CLI works fine.

**Comment by gmpinder** [comment]
Seems to have been a quoting issue in my bash. I've learned my lesson, put all variables in " and not on their own. Patch coming soon

**Comment by gmpinder** [comment]
https://github.com/blue-build/cli/commit/0b5e7599f89c5bdeb08201066d26e06517208b85
