### ISSUE TITLE
alt-tags key naming

### ISSUE THREAD

**Issue by xynydev** [blue-build/cli#179]
My mental model of this configuration option was "the default is latest+timestamp, but you can override if you want to", while the alt-tags: name sounds more like "latest+timestamp is the recommended way to tag, but you can swap it out for an alternative method". I'll make an issue about this too.

`image-tags:` was the name I originally suggested for this key, but I understand that might be confusing, as we also have `image-version:`. 

What do y'all think?

**Comment by gmpinder** [comment]
To be completely honest, I came up with that name without going back to the original thread. Now that you brought it up, I don't think `image-tags:` would have been clear enough. Since we haven't released official documentation for this property, I'm fine with renaming it to something else.

**Comment by gmpinder** [comment]
After conversations on discord, we're going to keep this as `alt-tags` for now and just proceed with working on recipe V2 (https://github.com/blue-build/cli/issues/180)
