### ISSUE TITLE
[BUG] build fails on github action 1.5.0 when base image doesn't follow semver (like coreos)

### ISSUE THREAD

**Issue by qoijjj** [blue-build/cli#183]
example:

```
[22:30:11 DEBUG] => Successfully inspected image docker://ghcr.io/ublue-os/ucore-minimal:stable!
[22:30:11 ERROR] => Unable to get the OS version from the labels. Please check with the image author about using 'org.opencontainers.image.version' to report the os version.
```

not reproducible on 1.3, or non-coreos based images

**Comment by gmpinder** [comment]
Issue stems from the fact that ucore doesn't follow semver 

```
$> skopeo inspect docker://ghcr.io/ublue-os/ucore-minimal:stable | jq -r '.Labels.["org.opencontainers.image.version"]'
40.20240416.3.1
```

This will require finding a way to handle a situation like this. Currently [semver](https://crates.io/crates/semver) doesn't support this, but it might be handled with [lenient_semver](https://crates.io/crates/lenient_semver). The only issue is that crate hasn't been updated in 3 years. I'll need to figure out how we can better handle this.
