### ISSUE TITLE
feat: support custom module repositories

### ISSUE THREAD

**Issue by gmpinder** [blue-build/cli#2]
This conversation was started in the Gitlab repo https://gitlab.com/wunker-bunker/blue-build/-/issues/4

**Comment by xynydev** [comment]
When launching a module from a custom repository, it should be given a custom value for the envvar `MODULE_DIRECTORY` like `/tmp/modules/ghcr.io-example-repo.

**Comment by xynydev** [comment]
Here's how I see this playing out.
- Add a new optional `source:` key to the module definition that point to an OCI image with modules at `/modules`. If unspecified, this would point to `ghcr.io/blue-build/modules` (future home of "bling").
- When compiling the recipe, do one pass gathering all the module sources as a deduped list, copying those modules necessary as talked about on Gitlab (but only once per source, to prevent creating a ton of extra layers with their content being removed in the final layer being created).
   - I *think* this is *probably* more efficient than just always copying...

**Comment by gmpinder** [comment]
> Add a new optional source: key to the module definition that point to an OCI image with modules at /modules. If unspecified, this would point to ghcr.io/blue-build/modules

What do you mean by that? Are you saying that the image name will always end in `/modules` or are you saying it will always have the files in `/modules` in the image?

**Comment by gmpinder** [comment]
Oh I think I know what you mean. If there isn't another source specified, it will just use the modules from `bling` (now `blue-build/modules`)

**Comment by xynydev** [comment]
I mean `/modules` as in the directory inside the container image containing all the modules and `ghcr.io/blue-build/modules` as our default module repository.

**Comment by gmpinder** [comment]
Ok, I have an idea on how to reduce the amount of `COPY` we do that will basically involve trying to mount some directory that will temporarily hold the module files and mount them during the `RUN` step for the module. That way the build has access to the files to run the modules but they aren't directly layered in.

Quick example:

```dockerfile
FROM ghcr.io/blue-build/modules AS module_name
RUN --mount=type=cache,id=bluebuild-modules-{{ build_id }},dst=/tmp/modules \
  cp -r /modules/* /tmp/modules/

FROM ghcr.io/ublue/main

RUN --mount=type=cache,id=bluebuild-modules-{{ build_id }},dst=/tmp/modules \
  /tmp/modules/module_name.sh
```

**Comment by gmpinder** [comment]
> That sounds good, but I can't understand much of what the Containerfile syntax is doing.
> 
> Is the `--mount` required for every `RUN` step to have access to the modules directory? How would third-party repositories be supported? Would they just be imported through that same `FROM` & `RUN` combo at the top, but use a different `id` for the mount?

It will be used for every `RUN` that has to deal with a module. We'll also be able to use a bind mount to mount in the config dir so that doesn't have to be copied in either. As for 3rd party repos, we could give it its own cache id and use that. We'll just keep them in the same `/tmp/modules` dir. This would help prevent any file conflicts

**Comment by xynydev** [comment]
> We'll just keep them in the same /tmp/modules dir. 

Nice! Would still need to add the `MODULE_DIRECTORY` env var, though...

**Comment by gmpinder** [comment]
> Nice! Would still need to add the `MODULE_DIRECTORY` env var, though...

For sure
