### ISSUE TITLE
instead of suffixing fedora version in tags, suffix the alt-tag   or `latest`

### ISSUE THREAD

**Issue by noahdotpy** [blue-build/cli#204]
Currently my tags look something like this for the alt-tags set as only `stable`:
```yml
# bluefin-dx:stable
Tags: [
    "40",
    "20240715-40",
    "stable",
    "0cb40ac-40",
]
```
The generated tags for `latest` channel of this same image is this:
```yml
# bluefin-dx:latest
Tags: [
    "40",
    "20240715-40",
    "latest",
    "0cb40ac-40",
]
```

As you can see there is very major overlap

Latest and stable are on the same fedora version but are actually quite significantly different ([see announcement of `stable` tag for bluefin](https://universal-blue.discourse.group/t/bluefin-and-aurora-3-0/2650#new-release-channels-3))

I think it would be better if the tags were like this instead, with everything suffixed with `-stable` (aka the alt-tag chosen:
```yml
# removed the 40 tag
Tags: [
    "20240715-stable",
    "stable",
    "0cb40ac-stable",
]
```

**Comment by xynydev** [comment]
I was initially shocked because I thought we'd specced out every overlap. But now I'm just thinking: *if `latest` and `stable` is the same version, why do you care about having separate tags?* 

I guess in my view the textual/numbered version tags are equivalent, with the textual ones being aliases to the numbered ones, but you are using them to mean something else?

**Comment by noahdotpy** [comment]
So in bluefin/aurora the `stable` tag is pretty much `latest` but with a gated kernel (from CoreOS stable), and it builds weekly.

**Comment by gmpinder** [comment]
Yeah I didn't really take into account using the same version number on the same image. Yeah I'm thinking that the proposed set of tags is the best way to handle this kind of thing. Then we can go back to having the timestamp tag but with `-alt-tag` tacked onto it.

**Comment by gmpinder** [comment]
We would still want to fully replace `latest` in the list of tags

**Comment by gmpinder** [comment]
This will need to wait until https://github.com/blue-build/cli/pull/197 is merged in.

**Comment by gmpinder** [comment]
@qoijjj as a heads up for future tag changes.

**Comment by noahdotpy** [comment]
How would it handle multiple `alt-tags`, would it pick the first one in the list?

**Comment by xynydev** [comment]
I think it would just create `xxx-alt-tag-one` and `xxx-alt-tag-two` separately. If you want a tag with multiple alt-tags listed, you don't want multiple alt-tags.
