### ISSUE TITLE
chore: Replace occurences of `/usr/etc/` to `/etc/`

### ISSUE THREAD

**Issue by fiftydinar** [blue-build/cli#213]
Reason why:
https://github.com/blue-build/modules/issues/314

**Comment by fiftydinar** [comment]
I'm reopening the issue, because it's reverted for now.

Signing files are not properly copied when put in `/etc/` in some builds, so `/usr/etc/` will be temporarily used until this gets fixed.

**Comment by gmpinder** [comment]
The patch is out and so is the change in modules. Closing
