### ISSUE TITLE
refactor: remove `yq`, rename `get_yaml_array` 

### ISSUE THREAD

**Issue by xynydev** [blue-build/cli#216]
Since the modules are provided their configuration as JSON, `yq` isn't AFAIK really needed anywhere anymore, it's just used in most modules. We should first check if the modules repo still needs `yq`, and if not, replace it with `jq`. If we [start using Nushell](https://github.com/blue-build/modules/issues/212) for some modules, it has built-in YAML capabilities wherever that might be needed.

**Comment by gmpinder** [comment]
Closing in favor of #261
