### ISSUE TITLE
fix: Image parsing error due to uppercase username

### ISSUE THREAD

**Issue by Tikaiz1** [blue-build/cli#225]
I am having an error building my image, as it is not successfully parsed, this is because of a recent update in the cli tool which previously converted usernames to lowercase and in the latest version it no longer does that.
My GitHub username contains uppercase characters which docker doesn't support pulling from and so the build fails.

The error is as follows:
```
[08:52:49 ERROR] => Failed:
  × Unable to parse image ghcr.io/Tikaiz1/bazzite-tikaiz
  ╰─▶ invalid reference format

Error: Process completed with exit code 1.
```

**Comment by arminmiau** [comment]
I believe this could be because all to_lowercase calls were removed in this commit: https://github.com/blue-build/cli/commit/2f3edeb1a537e75eedf65f295fadf586d19531b9

**Comment by gmpinder** [comment]
Yup, that's my fault. Here's the fix https://github.com/blue-build/cli/commit/8c94473ae39233dd9c31ad7085c0deb245ed29c0

I'm getting a patch out today
