### ISSUE TITLE
`generate-iso`: If `bootupctl backend generate-update-metadata` is not run in the image, ISO install fails

### ISSUE THREAD

**Issue by fiftydinar** [blue-build/cli#227]
This means that `bootc` needs to be installed inside the image for the command to be performed.

Jason's Wiki which acknowledges this:
https://github.com/JasonN3/build-container-installer/wiki/known_errors#failed-to-write-boot-loader-configuration

We can either recommend or automate this.

This package is available from F39+, but F39 ships older version, which is not tested.

Will also have to check out if F41 Beta has `bootc` installed, so we wouldn't need to do the package install for F41+.

**Comment by gmpinder** [comment]
I think a post-install script that is run at the end of the build is the best way to handle this. I can do some local testing to see if the the F39 images will work with that version of bootc. A general check for the existence of the binary can be done and then we can perform an install in the event that it isn't installed. That should cover most bases here.
