### ISSUE TITLE
feat: Create a builtin module for rpm-ostree

### ISSUE THREAD

**Issue by gmpinder** [blue-build/cli#24]
We should pull in logic for running the `rpm-ostree` module into the template. This will allow us to take advantage of using [cache mounts](https://www.mankier.com/5/Containerfile#Format) to help speed up builds as updating the `rpmdb` is a slow process during builds.

**Comment by xynydev** [comment]
Do the cache mounts also provide benefits in CI/CD with ephemeral builders?

**Comment by gmpinder** [comment]
> Do the cache mounts also provide benefits in CI/CD with ephemeral builders?

Unfortunately it would only benefit local builds unless a user had their own runner setup for their repo.

**Comment by gmpinder** [comment]
Ok so rather than taking over the rpm-ostree module as a whole, the cli is just going to have a cache mount. With how complex the rpm-ostree module could get, I think it would be best to keep it as a script module.
