### ISSUE TITLE
Please add a label containing digest of the `base-image` used for the build

### ISSUE THREAD

**Issue by yacoob** [blue-build/cli#263]
I'd like to know what was the specific underlying `base-image` used during the build. Would it be possible to add a label on the produced image that reflects this?

Context: I'm trying to avoid rebuilding my own custom image, unless the base image has been updated. Right now I [save that digest during the build](https://github.com/yacoob/yaurora/blob/main/.github/workflows/build.yaml#L29-L33) and [compare it against current registry digest](https://github.com/yacoob/yaurora/blob/main/.github/workflows/maybe_build.yaml), but it's a bit clunky and brittle approach. Having this as a label on the final image would be way more convenient.

I'm willing to make a PR to add this, if you'd show me in cli's code where would be a good place to extract that information during build time. My Rust is rather rusty (heh :) so it'd speed things up.

Thanks!

**Comment by yacoob** [comment]
From a cursory inspection of the source, it looks like `bluebuild` doesn't really get involved in the building process itself; it generates the `Containerfile` and asks the build driver to use it. Which means, whatever it does in order to devise digest of the `base-image`, it's exposed to the same timing problem as my current solution. I haven't found a way to get that digest within the `Containerfile` itself either. :(

Do you think it's worthwhile to add any post-build labeling here, which might be stale? Or is that something that you don't want `bluebuild` to worry about?

**Comment by gmpinder** [comment]
So if what you need is a label on your image that contains the digest of the base image used to build your image, I can very easily add that to the build. We already inspect the base image for various other information.

**Comment by yacoob** [comment]
Thanks!

...so out of curiosity, how are you handling that race condition right now?  :)

**Comment by gmpinder** [comment]
> Thanks!
> 
> ...so out of curiosity, how are you handling that race condition right now?  :)

There isn't a race condition. BlueBuild creates the containerfile for you and then uses that to build your image. All the inspection is done before we generate the containerfile.

**Comment by yacoob** [comment]
I've checked the output of the generated `Containerfile` and it's:

```
FROM ghcr.io/ublue-os/aurora-dx:stable AS yaurora
```
If `bluebuild` is inspecting `aurora-dx:stable` before generating this, there's a small window of time between inspection and actually using the generated `Containerfile`, where `aurora-dx:stable` might be updated (by `ublue-os`). That's what I'm referring to as a race condition. The time window is small, but non-zero :) Maybe it hasn't been a concern on your end.

If you want to entertain this problem further, I see two approaches this can be mitigated with:

- Resolve `base-image` outside of the `Containerfile` down to specific digest, use that digest in `FROM` line of the generated `Containerfile` (eg. `FROM image@digest ...`).
- Label the image post-build, based on the produced build driver logs. That's going to be my workaround once/if https://github.com/blue-build/github-action/pull/66 gets merged.

**Comment by gmpinder** [comment]
> there's a small window of time between inspection and actually using the generated Containerfile, where aurora-dx:stable might be updated (by ublue-os).

This is really not a problem since it's far less than a second from when the image is inspected and your image starts building. We can still use the digest to be sure, but this is highly unlikely to be a problem from within the CLI.

**Comment by yacoob** [comment]
Thanks a lot for this! It really simplified my GH action :)
