### ISSUE TITLE
As of today, builds are failing due to the jq changes

### ISSUE THREAD

**Issue by RoyalOughtness** [blue-build/cli#285]
```
/tmp/modules/script/script.sh: line 6: get_json_array: command not found
```

Happens even when the cli is upgraded to 0.8.25

**Comment by gmpinder** [comment]
Can you give us a link to the failing build?

**Comment by RoyalOughtness** [comment]
https://github.com/secureblue/secureblue/actions/runs/12128650515/job/33815463816?pr=632

**Comment by gmpinder** [comment]
Looks like you have a step downloading `v0.8.20` https://github.com/secureblue/secureblue/pull/632/checks#step:5:12
