### ISSUE TITLE
New `validate` is choking on numeric `gnome-extensions`

### ISSUE THREAD

**Issue by dperson** [blue-build/cli#286]
Error on build:
```
[16:44:08 ERROR] => Failed:

  × Recipe ./recipes/recipe.yml failed to validate
  ╰─▶ 
        × 1 error encountered
           ╭─[./recipes/recipe.yml:267:9]
       266 │
       267 │ ╭─▶   - type: gnome-extensions
       268 │ │       install:
       269 │ │         - 615 # appindicatorsupport@rgcjonas.gmail.com
       270 │ │         - 16 # auto-move-windows@gnome-shell-
      extensions.gcampax.github.com
       271 │ │         - 6670 # Bluetooth-Battery-Meter@maniacx.github.com
       272 │ │         - 3193 # blur-my-shell@aunetx
       273 │ │         - 517 # caffeine@patapon.info
       274 │ │         - 4839 # clipboard-history@alexsaveau.dev
       275 │ │         - 307 # dash-to-dock@micxgx.gmail.com
       276 │ │         - 28 # gTile@vibou
       277 │ │         - 3843 # just-perfection-desktop@just-perfection
       278 │ │         - 7048 # rounded-window-corners@fxgn
       279 │ ├─▶       - 6139 # tailscale@joaophi.github.com
           · ╰──── is not valid under any of the schemas listed in the 'anyOf'
      keyword
       280 │
           ╰────
        help: Try adding these lines to the top of your file:
              ---
              # yaml-language-server: $schema=https://schema.blue-/
      build.org/recipe-
              v1.json
      
  help: Use `bluebuild validate --all-errors ./recipes/recipe.yml` to view
        more information.
        If you're using a local module, be sure to add `source: local` to the
        module entry
```

Thanks!

**Comment by dperson** [comment]
FYI related to the `hint`, I'd already added the suggested lines at the top of my recipe:
```
 ---
 # yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
```
When I merged the updated template.

**Comment by xynydev** [comment]
That line adds IDE support, the error should be highlighted if your editor support the language server. It's hard to see what the error is otherwise. However, I have a pretty good idea of what the issue is so I'll go fix that and ask you to report back afterwards.

**Comment by dperson** [comment]
FYI @xynydev:
@gmpinder may also be looking at this (originally posted the question on Mastodon), just so you both don't try to fix the schema only supporting strings and not numbers (which he said he thought the issue was.

**Comment by xynydev** [comment]
I'm actually in charge of the BlueBuild account, so it was me who had that theory all along. That issue should be fixed now. The schema file may be cached locally, but re-running a build on GitHub should have the schema updates right away.

**Comment by gmpinder** [comment]
> I'm actually in charge of the BlueBuild account, so it was me who had that theory all along. That issue should be fixed now. The schema file may be cached locally, but re-running a build on GitHub should have the schema updates right away.
> 
> [blue-build/modules@a044f60](https://github.com/blue-build/modules/commit/a044f600cac9847a476a6da184bfa53a8d912faf)

Thanks for taking care of that! Also the schema files are downloaded pretty much every time the command is run

**Comment by gmpinder** [comment]
> That line adds IDE support, the error should be highlighted if your editor support the language server. It's hard to see what the error is otherwise. However, I have a pretty good idea of what the issue is so I'll go fix that and ask you to report back afterwards.

I should probably update the help text to better communicate the intention

**Comment by dperson** [comment]
Okay, well thank you both! Re-running the build now, I'll close on success.

**Comment by dperson** [comment]
Yep that fixed it! Thank you so much!
