### ISSUE TITLE
feat: Improve module logging

### ISSUE THREAD

**Issue by xynydev** [blue-build/cli#36]
Startingpoint's build.sh prints `=== Launching module of type: $TYPE ===` when launching a module and `======` after a module is finished. This tidies up the logs a little.

Would y'all think that it's a good idea to add these echoes to the generated Containerfile? Another option would be to add them manually in each module, but that feels like it's the wrong place.

**Comment by fiftydinar** [comment]
Another good suggestion is to add newlines in some areas, to separate things better.

**Comment by bayou-brogrammer** [comment]
I hate the logging. We should definitely clean it up

**Comment by gmpinder** [comment]
The logger format can easily be updated as we use [env_logger](https://docs.rs/env_logger/latest/env_logger/). We should still keep the logs in there as it is super important for debugging issues, but if you want to make some logs nicer on the eyes I'm all for it.

**Comment by xynydev** [comment]
The container build time logging is still something that has to be coded manually.

**Comment by gmpinder** [comment]
> The container build time logging is still something that has to be coded manually.

You're talking about the echos for each module? Adding those would be super easy

**Comment by xynydev** [comment]
It would.

**Comment by fiftydinar** [comment]
It would be great if logs could be separated somehow. Like show module logs by default (like in legacy template) & make showing bluebuild-cli logs optional

**Comment by gmpinder** [comment]
> It would be great if logs could be separated somehow. Like show module logs by default (like in legacy template) & make showing bluebuild-cli logs optional

You can with the `-q` arg reduce the log level and use `-v` increase the log level.

Also since we're calling other programs to build, it'll be way harder to try to extract the relevant lines from the output and subject to breakage if the output of those programs changes its shape. I'm all for making the logs look nicer, but I want to keep realistic expectations on what we can do. Now if you're suggesting we add some echo statements into the template, then that would be perfectly doable.

**Comment by xynydev** [comment]
IMO some echos in the template would be nice for readability's sake anyways.

**Comment by xynydev** [comment]
Did you add echos in the template?

**Comment by gmpinder** [comment]
> Did you add echos in the template?

Yup that was in the recent PR
