### ISSUE TITLE
Remove input of recipe.yml file for `bb build`

### ISSUE THREAD

**Issue by bayou-brogrammer** [blue-build/cli#39]
There was some discussion between @xynydev and I about how the config should live in a set destination. I think right now we have it live at `config/recipe.yml`. Should we just default to this file if none provided?

**Comment by xynydev** [comment]
Yeah, that should be the default, but it should also be *possible* to use an arbitrary location.

**Comment by gmpinder** [comment]
So the command would be something more like:

```rust
pub struct TemplateCommand {
    /// The recipe file to create a template from
    #[arg()]
    #[builder(setter(into))]
    recipe: Option<PathBuf>,

    /// File to output to instead of STDOUT
    #[arg(short, long)]
    #[builder(default, setter(into, strip_option))]
    output: Option<PathBuf>,
}
```
