### ISSUE TITLE
refactor: clean standard implementation of cli modules

### ISSUE THREAD

**Issue by xynydev** [blue-build/cli#40]
Currently with the modules all being declared first as functions and then as if-statements in the template, the system looks kind of hacked together to me. It'd be nicer to have a module be able to be in it's own file, and just a function that outputs a string or something, as it is likely that the amount of transpiler modules will increase. 

Each module here should also have it's module.yml, readme and a jsonschema file for generating a reference on the website. That probably requires each module to have its own directory.

**Comment by gmpinder** [comment]
I agree with this. Ever since I wrote the logic for flattening the recipe for the bug report (pulling in the `from-file` contents) I've been wanting to do that for the main Containerfile template so that we don't have to recursive templating. We could kill two birds with one stone on this issue.
