### ISSUE TITLE
Should we provide modules that allow running commands directly?

### ISSUE THREAD

**Issue by xynydev** [blue-build/cli#41]
Currently both the script and containerfile modules take in files, but someone might want to just run a single bash or Containerfile command command. It would be more convenient to include that snippet directly in the module configuration.

This feature could be trivially implemented in the same modules without breaking anything like so:

```yaml
type: script
scripts:
    - ...
snippets:
    - curl ... | bash
```
```yaml
type: containerfile
containerfiles:
    - ...
snippets:
    - COPY --from ...
```

Could also create separate modules, and that'd keep the module names more meaningful, but also be more cluttered.

**Comment by gmpinder** [comment]
Maybe we call it a `command` type of module?

**Comment by xynydev** [comment]
Not sure what you mean by that; Are you suggesting separate modules be created?

**Comment by gmpinder** [comment]
> Not sure what you mean by that; Are you suggesting separate modules be created?

Yeah a module type called commands or command. Each entry could be it's own run command

**Comment by gmpinder** [comment]
But if we want to do snippets for script and containerfile types, that would be easy to implement

**Comment by bayou-brogrammer** [comment]
> But if we want to do snippets for script and containerfile types, that would be easy to implement

This is a very simple solution to our side, but for creating a separate module, I do see the benefits, but also the drawbacks.

Im trying to understand the pros and cons of each choice.

### **New Module**
#### __pros__
- Keeps cli code clean (no extra code)
- easily implemented for users in their recipe file

#### _cons_
- requires maintenance from core team (or user)
- creates a separation in the yml file potentially

### **Builtin CLI**
#### _cons_
- easy to implement
- maintained as part of CLI devs
- the snippet code is injected directly into the container file right after modules run

#### _cons_
- messier codebase
- messier containerfile

**Comment by xynydev** [comment]
@bayou-brogrammer you're putting only _creating a new module_ and _creating some new type of thing that is definetly not a module and used in a different way and only available with cli_. I am 100% against the latter.

What I'd choose to do here if this is a feature we want to support is the solution I described at the top of this thread, and @bayou-brogrammer didn't do pros/cons for at all; adding this to the script and containerfile modules. The script module snippets would be implemented in the script module, and the containerfile snippets here with the cli. 

The reason I don't like the idea of making a new module for this is that I feel like these features already exists in a *slightly different way* with the old modules. 

The `command` module is in my eyes just a worse version of both the containerfile and script modules, so I am not keen on that idea either.

**Comment by gmpinder** [comment]
> The script module snippets would be implemented in the script module, and the containerfile snippets here with the cli.

Yeah I'm starting to come around on this idea. So snippets would be extremely useful for these two separate modules (`script` and `containerfile`).

For instance the `script` module. The snippets would allow the user to just add single commands that they would like to run without the need to create a full on bash script. Perfect for one line installs using a `curl` command to pipe the script into `bash`. These could end up being either each their own `RUN` layer or combined into a single one using `&&`.

For the `containerfile` we would allow the user to put a new command layer like if they're trying to `COPY` something from another image or want to have a custom `RUN` layer and make use of mounts if they so wish. Keeping it as separate functionality from how a `script` snippet would work.

In my opinion, adding snippets for any module would be confusing/counter-intuitive to the original intent of the module itself.

**Comment by xynydev** [comment]
> These could end up being either each their own `RUN` layer or combined into a single one using `&&`.

Keep in mind that this is a bash module. It would be trivial to just `eval` the provided commands in the current code, without a need to touch the cli codebase.

**Comment by gmpinder** [comment]
> Keep in mind that this is a bash module. It would be trivial to just `eval` the provided commands in the current code, without a need to touch the cli codebase.

That's right, I forgot about that. Well in that case it would require a change in the `bling` side of things for `script` snippets. I still think that Containerfile line snippets should only be in the `containerfile` module type.

**Comment by bayou-brogrammer** [comment]
> The command module is in my eyes just a worse version of both the containerfile and script modules, so I am not keen on that idea either.

I agree with this. Out of all solutions, this seems the worst.

I like the idea of having the script module take the responsibility of owning snippets and the containerfile module being cli responsibility, but I don't see why the containerfile would want snippets in the first place. That module already injects snippets into the containerfile from the current implementation

**Comment by gmpinder** [comment]
> I like the idea of having the script module take the responsibility of owning snippets and the containerfile module being cli responsibility, but I don't see why the containerfile would want snippets in the first place. That module already injects snippets into the containerfile from the current implementation

It requires specifying what folder in `./config/containerfile` holds a `Containerfile`. So say you want to orchestrate some custom `Containerfile` commands and want to store files related to it in there. So in the current implementation you could have:

```yaml
name: jp-desktop
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: latest
description: The image of Wunker OS for JP's desktop.
modules:
  - type: files
    files:
      - 8bitdo-ultimate: /usr
      - steam-firewall: /usr
      - desktop-audio: /usr
  - type: containerfile
    containerfiles:
      - xboxdrv
  - from-file: jp-apps.yml
```

Which would then look in `./config/containerfiles/xboxdrv/` for a `Containerfile`. This file could be:

```dockerfile
COPY --from=registry.gitlab.com/wunker-bunker/xboxdrv-docker /usr/local/bin/xboxdrv /usr/bin/xboxdrv
COPY --from=registry.gitlab.com/wunker-bunker/xboxdrv-docker /usr/local/bin/xboxdrvctl /usr/bin/xboxdrvctl
COPY --from=registry.gitlab.com/wunker-bunker/xboxdrv-docker /usr/local/share/man/man1/xboxdrv.1 /usr/share/man/man1/xboxdrv.1
COPY ./config/containerfiles/xboxdrv/setup.sh /tmp/setup.sh
RUN /tmp/setup.sh
LABEL some-label.id="id"
```

And it would print those contents into the generated `Containerfile` that is then used to build your image. This allows for a lot of granular control over any extra layers the user wants to add, but it is more complex. 

Having a `snippets` section would make it so that you don't have to create those extra files if you don't need them and you can just specify a layer(s) you want to add directly in your recipe.yml.

**Comment by bayou-brogrammer** [comment]
> > I like the idea of having the script module take the responsibility of owning snippets and the containerfile module being cli responsibility, but I don't see why the containerfile would want snippets in the first place. That module already injects snippets into the containerfile from the current implementation
> 
> It requires specifying what folder in `./config/containerfile` holds a `Containerfile`. So say you want to orchestrate some custom `Containerfile` commands and want to store files related to it in there. So in the current implementation you could have:
> 
> ```yaml
> name: jp-desktop
> base-image: ghcr.io/ublue-os/kinoite-nvidia
> image-version: latest
> description: The image of Wunker OS for JP's desktop.
> modules:
>   - type: files
>     files:
>       - 8bitdo-ultimate: /usr
>       - steam-firewall: /usr
>       - desktop-audio: /usr
>   - type: containerfile
>     containerfiles:
>       - xboxdrv
>   - from-file: jp-apps.yml
> ```
> 
> Which would then look in `./config/containerfiles/xboxdrv/` for a `Containerfile`. This file could be:
> 
> ```dockerfile
> COPY --from=registry.gitlab.com/wunker-bunker/xboxdrv-docker /usr/local/bin/xboxdrv /usr/bin/xboxdrv
> COPY --from=registry.gitlab.com/wunker-bunker/xboxdrv-docker /usr/local/bin/xboxdrvctl /usr/bin/xboxdrvctl
> COPY --from=registry.gitlab.com/wunker-bunker/xboxdrv-docker /usr/local/share/man/man1/xboxdrv.1 /usr/share/man/man1/xboxdrv.1
> COPY ./config/containerfiles/xboxdrv/setup.sh /tmp/setup.sh
> RUN /tmp/setup.sh
> LABEL some-label.id="id"
> ```
> 
> And it would print those contents into the generated `Containerfile` that is then used to build your image. This allows for a lot of granular control over any extra layers the user wants to add, but it is more complex.
> 
> Having a `snippets` section would make it so that you don't have to create those extra files if you don't need them and you can just specify a layer(s) you want to add directly in your recipe.yml.

The last line convinced me. Not having to abstract something really small like a couple of lines into another folder would be annoying

**Comment by gmpinder** [comment]
Ok so it's agreed @xynydev @bayou-brogrammer ? This feature will add `snippets` as a possible field for the `containerfile` module that will just print out each entry of the `snippets` array into the resulting `Containerfile` that is used to build.
