### ISSUE TITLE
feat: Add a check for an uncommitted Containerfile

### ISSUE THREAD

**Issue by gmpinder** [blue-build/cli#56]
This was brought up by @bayou-brogrammer in our discord. With people moving from starting point to BlueBuild, they might have some changes in their Containerfile that they might not want to lose. 

Some basic requirements:

- If the file is dirty, the CLI should:
  - allow a force flag to just brute force it
  - error out and give a message that they should either commit the file or add force flag
- Check if the file is in .gitignore, if it is don't bother with the check

**Comment by gmpinder** [comment]
We could also have a check for a label or comment in the file that indicates to the tool that it was generated. This way we don't bombard the user with an error everytime and is only used when migrating to BlueBuild from starting point.

**Comment by xynydev** [comment]
Good idea
