### ISSUE TITLE
improve: add retries for pushes/pulls from GHCR

### ISSUE THREAD

**Issue by qoijjj** [blue-build/cli#79]
A small percentage of the time, calls to push or pull blobs from GHCR fail with 502 Bad Gateway. Adding a single retry to these requests will improve reliability and prevent the need to rerun failed jobs frequently. Example:

```
error pushing image "ghcr.io/secureblue/bluefin-main-laptop-hardened:20240222" to "docker://ghcr.io/secureblue/bluefin-main-laptop-hardened:20240222": trying to reuse blob sha256:68285333949b6a5f2ed1df59871327faf019ae8593c288b7ecb933a07abcf9e6 at destination: failed to read from destination repository secureblue/bluefin-main-laptop-hardened: 502 (Bad Gateway)
```

**Comment by bayou-brogrammer** [comment]
Oh yeah we can use the retry action like uBlue does

**Comment by xynydev** [comment]
I think this retry should be added cli-side, because the retry action felt kind of hacky last time I looked at it, and it will try to retry if any part of the build fails, not just on nondetermenisticn podman errors.

**Comment by bayou-brogrammer** [comment]
> I think this retry should be added cli-side, because the retry action felt kind of hacky last time I looked at it, and it will try to retry if any part of the build fails, not just on nondetermenisticn podman errors.

curious how this would translate. Would we just retry the entire build if the `bluebuild build` returns an exit code != 0?

**Comment by qoijjj** [comment]
@bayou-brogrammer 

No you should just need to add a retry inside of specific calls made in the cli, like here:

https://github.com/blue-build/cli/blob/681aab4a85c7c5a016ef1b064b9668fd518cc04c/src/commands/build.rs#L1012
