### ISSUE TITLE
bug: Forward slash (`/`) character not replaced in tag reference

### ISSUE THREAD

**Issue by CarrotManMatt** [blue-build/cli#92]
As mentioned by @gmpinder in [blue-build/discussions/12](https://github.com/orgs/blue-build/discussions/12), an error occurs when using the latest version of the github action, which is caused by the blue-build CLI tool not correctly replacing the forwards slash (`/`) character within the generated tags, by the CLI.

See this failing build: https://github.com/CarrotManMatt/carrot-kinoite-nvidia/actions/runs/8055478674/job/22002432608

Example tag that causes a build failure: `ghcr.io/carrotmanmatt/carrot-kinoite-nvidia:br-dependabot/github_actions/blue-build/github-action-1.1.0-39`

**Comment by CarrotManMatt** [comment]
Thank you for fixing this so speedily!❤

What steps must I take so that I can successfully rerun my build, now that this has been fixed? Or do I need to wait for some sort of release?

**Comment by xynydev** [comment]
There's no way to use a non-released version currently, so you need to wait for a release. There's a tracking issue: https://github.com/blue-build/github-action/issues/17

Fortunately this only has to do with the branch tags, so you can hopefully live without for now, right?

**Comment by CarrotManMatt** [comment]
> Fortunately this only has to do with the branch tags, so you can hopefully live without for now, right?

I presume so, as when I merge the update the main build will succeed, even if the merge request one is failing👍🏻
