### ISSUE TITLE
v1.1.x breaks some images with an error about content in var

### ISSUE THREAD

**Issue by qoijjj** [blue-build/cli#95]
```
Found file: var/lib/alternatives/ld
error: Found content in var
```

https://github.com/secureblue/secureblue/actions/runs/8068238477/job/22040524220#step:8:999

Does not occur on 1.0.2.

**Comment by gmpinder** [comment]
So it seems like this directory was created outside a module. In our attempt to use tmpfs mounts for var, we didn't consider users/base images put content in there. We'll have to add back the rm for tmp and var to keep this working.

**Comment by qoijjj** [comment]
@gmpinder it's not something we (secureblue) are doing since we made no changes to those images, so it's likely something happening in ucore. To be clear, it's only the ucore-nvidia images we're seeing this in:

https://github.com/ublue-os/ucore/blob/main/ucore/Containerfile

**Comment by gmpinder** [comment]
> @gmpinder it's not something we (secureblue) are doing since we made no changes to those images recently, so it's likely something happening in ucore. To be clear, it's only the ucore-nvidia images we're seeing this in:
> 
> https://github.com/ublue-os/ucore/blob/main/ucore/Containerfile

Right I'm saying this is on us to fix

**Comment by qoijjj** [comment]
@gmpinder I know, I was just adding some additional context :smile:
